DROP TABLE IF EXISTS movies;

CREATE TABLE movies (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  release_year INTEGER NOT NULL,
  rating VARCHAR(5) NOT NULL,
  rotten_tomatoes VARCHAR(255) NOT NULL,
  poster VARCHAR (255) NOT NULL
);
